version: '3.8'

services:
  # 🗄️ PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: iotrix-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-iotdb}
      POSTGRES_USER: ${POSTGRES_USER:-iotrix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-securepassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-iotrix}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - iotrix-network

  # 🐍 Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iotrix-backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER:-iotrix}:${POSTGRES_PASSWORD:-securepassword}@database:5432/${POSTGRES_DB:-iotdb}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - iotrix-network

  # ⚛️ Frontend
  frontend:
    build:
      context: ./iotrix-frontend
      dockerfile: Dockerfile
    container_name: iotrix-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - iotrix-network

  # 🔄 Redis (Optional - for caching)
  redis:
    image: redis:7-alpine
    container_name: iotrix-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - iotrix-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  iotrix-network:
    driver: bridge
